# -*- coding: utf8 -*-

class CadcConf:
    domainMappings: dict
    confFile: str
    confDict: str

    def __init__(self, confFile: str): ...
    def __checkProviderDomains(self, providerIdx: int, provider: dict, domains: list) -> None: ...
    def __checkProviderAliyun(self, providerIdx: int, provider: dict) -> None: ...
    def __checkProviders(self, providers: list) -> None: ...
    def check(self) -> None: ...
